# Generated by Django 5.1.3 on 2024-11-15 10:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='subject',
            name='backlogs',
            field=models.CharField(default='No Backlogs', max_length=400),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subject',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='board',
            field=models.CharField(blank=True, choices=[('BSEB', 'BSEB'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PhD', 'PhD'), ('BSc', 'BSc'), ('MSc', 'MSc'), ('BA', 'BA'), ('MA', 'MA'), ('MBA', 'MBA'), ('B.Ed', 'B.Ed'), ('M.Ed', 'M.Ed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]