# Generated by Django 5.1.3 on 2024-11-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0003_remove_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
