# Generated by Django 5.1.3 on 2024-11-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
