# Generated by Django 5.1.3 on 2024-11-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0008_alter_teacher_qualification_alter_teacher_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherhire.teacher'),
        ),
    ]
