# Generated by Django 5.1.3 on 2024-11-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0009_alter_rating_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherhire.teacher'),
        ),
    ]
