# Generated by Django 5.1.3 on 2024-11-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0006_adminlogin'),
        ('teacherhire', '0010_alter_rating_teacher'),
    ]

    operations = [
    ]
