# Generated by Django 5.1.3 on 2024-11-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0018_alter_qualification_user_id_alter_skill_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='user_id',
        ),
    ]
