# Generated by Django 5.1.3 on 2024-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0023_remove_teacher_subject_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='teacherhire.subject'),
        ),
    ]
