# Generated by Django 5.1.3 on 2024-11-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0024_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(related_name='teachers', to='teacherhire.subject'),
        ),
    ]
